import type { Role } from "../types/domain";

export const PERMISSIONS = {
  VIEW_MANAGEMENT_DASHBOARD: "VIEW_MANAGEMENT_DASHBOARD",
  VIEW_CLASSES: "VIEW_CLASSES",
  MANAGE_CLASSES: "MANAGE_CLASSES",
  VIEW_MANAGEMENT_SCHEDULE: "VIEW_MANAGEMENT_SCHEDULE",
  MANAGE_SESSION_SCHEDULE: "MANAGE_SESSION_SCHEDULE",
  VIEW_OWN_SCHEDULE: "VIEW_OWN_SCHEDULE",
  VIEW_OWN_TEACHING: "VIEW_OWN_TEACHING",
  EDIT_OWN_SESSION_RECORDS: "EDIT_OWN_SESSION_RECORDS",
  MANAGE_SESSION_VERIFICATION: "MANAGE_SESSION_VERIFICATION",
  VIEW_FINANCE: "VIEW_FINANCE",
  VIEW_PLATFORM_TENANTS: "VIEW_PLATFORM_TENANTS",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const rolePermissions: Record<Role, Permission[]> = {
  SUPER_ADMIN: [PERMISSIONS.VIEW_PLATFORM_TENANTS],
  ADMIN: [
    PERMISSIONS.VIEW_MANAGEMENT_DASHBOARD,
    PERMISSIONS.VIEW_CLASSES,
    PERMISSIONS.MANAGE_CLASSES,
    PERMISSIONS.VIEW_MANAGEMENT_SCHEDULE,
    PERMISSIONS.MANAGE_SESSION_SCHEDULE,
    PERMISSIONS.MANAGE_SESSION_VERIFICATION,
    PERMISSIONS.VIEW_FINANCE,
  ],
  ACADEMIC_MANAGER: [
    PERMISSIONS.VIEW_MANAGEMENT_DASHBOARD,
    PERMISSIONS.VIEW_CLASSES,
    PERMISSIONS.MANAGE_CLASSES,
    PERMISSIONS.VIEW_MANAGEMENT_SCHEDULE,
    PERMISSIONS.MANAGE_SESSION_SCHEDULE,
    PERMISSIONS.MANAGE_SESSION_VERIFICATION,
  ],
  ACCOUNTANT: [
    PERMISSIONS.VIEW_CLASSES,
    PERMISSIONS.VIEW_MANAGEMENT_SCHEDULE,
    PERMISSIONS.VIEW_FINANCE,
  ],
  TEACHER: [
    PERMISSIONS.VIEW_OWN_SCHEDULE,
    PERMISSIONS.VIEW_OWN_TEACHING,
    PERMISSIONS.EDIT_OWN_SESSION_RECORDS,
  ],
  STUDENT: [],
};

export const getPermissions = (roles: Role[]): Set<Permission> =>
  new Set(roles.flatMap((role) => rolePermissions[role]));

export const hasPermission = (roles: Role[], permission: Permission): boolean =>
  getPermissions(roles).has(permission);

export const roleLabels: Record<Role, string> = {
  SUPER_ADMIN: "Super Admin",
  ADMIN: "Admin trung tâm",
  ACADEMIC_MANAGER: "Quản lý học vụ",
  ACCOUNTANT: "Kế toán",
  TEACHER: "Giáo viên",
  STUDENT: "Học sinh",
};
